drum_name_dict = {"KICK": 0,
               "SNARE": 0,
               "CLAP": 0,
               "HHAT": 0, 
               "RIM": 0,
               "BELL": 0,
               "CRASH": 0,
               "OHAT": 0,
               "MARACA": 0,
               "CLAV": 0,
               "TOM L": 0,
               "TOM M": 0,
               "TOM H": 0,
               "CONGA L": 0,
               "CONGA M": 0,
               "CONGA H": 0,}